### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by YannickFricke** [alongubkin/store#10]
Hey there,

I would try the plugin but I can't cause you cant download the webinterface anymore. So please update the wiki and please provide a downloadlink for the Webinterface.

Thanks in advance :)

**Comment by Gatherix** [comment]
The Store thread on AlliedModders provides links to all the resources needed to setup the plugin on a prepared server, including a working link to the latest version of the webpanel. The link in the Wiki here on GitHub is simply outdated. Refer to the Webpanel's thread or its corresponding Git repository.

https://forums.alliedmods.net/showthread.php?p=1883525

**Comment by Arrow768** [comment]
I have updated the link to the webpanel wiki in the tutorial
