### ISSUE TITLE
Error 1054

### ISSUE THREAD

**Issue by Dunkstormen** [alongubkin/store#12]
Error Number: 1054

Unknown column 'flags' in 'field list'

INSERT INTO `store_items` (`name`, `display_name`, `description`, `web_description`, `type`, `loadout_slot`, `price`, `attrs`, `is_buyable`, `is_tradeable`, `is_refundable`, `category_id`, `expiry_time`, `flags`) VALUES ('h', 'h', 'h', 'h', 'trails', 'trails', '1', '{\n \"material\": \"materials/sprites/store/trails/8bitmushroom.vmt\",\n \"lifetime\": 1,\n \"width\": 15,\n \"endwidth\": 6,\n \"fadelength\": 1\n}', '1', '1', '1', '11', NULL, NULL)

Filename: /data/filer-6/web/web1670/htdocs/store-webpanel-master/models/items_model.php

Line Number: 224

**Comment by ghost** [comment]
Update your store database.
https://github.com/alongubkin/store/blob/development/configs/store/sql-init-scripts/1.1.1-alpha%20to%201.2-beta.sql

**Comment by Dunkstormen** [comment]
Thank you ;)
