### ISSUE TITLE
!accept gift doesn't work

### ISSUE THREAD

**Issue by Ygnas** [alongubkin/store#13]
Tried to gift a Tittle in game, getting the message about type !accept to get your gift, but by doing so nothing happens.

no errors in log file. Using development release cause stable one is not working

**Comment by Arrow768** [comment]
Try using store-gifting from the stable branch

**Comment by Chdata** [comment]
To add on to this, there's other times where Store_RegisterChatCommands() fails.

"credits_commands"          "!bit !bits /bit /bits !credits /credits !credit /credit"

Only /bit and /bits work, but neither of /credit or /credits works.

Setting "creditsModel"              "models/items/currencypack_medium.mdl"
in gifting.cfg does not work.

I later edited the .sp file itself and the same model string worked just fine.

I even did this to the .sp:

KvGetString(kv, "credits_commands", buffer, sizeof(buffer), "!bits /bits !bit /bit /credits !credits");

native KvGetString(Handle:kv, const String:key[], String:value[], maxlength, const String:defvalue[]="");

Yet /credits (the default value) doesn't work.
