### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by shtspk** [alongubkin/store#30]
I have this problem, 

Error Number: 1054

Unknown column 'email' in 'field list'

SELECT `email`, `username`, `email`, `id`, `password`, `active`, `last_login` FROM (`store_users`) WHERE `email` = 'admin' LIMIT 1

Filename: /home2/rptbrcom/public_html/store/models/ion_auth_model.php

Line Number: 866

**Comment by Arrow768** [comment]
Wrong repo.
